name: dingdong_flutter
description: A Flutter project called dingdong

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flukit:
    path: package_src
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.5.0
  dio: ^2.1.1
  flutter_swiper : ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - images/green.jpg
  - images/red.jpg
  - images/green2.png
  - images/red2.png
